# Generated by Django 4.2.11 on 2024-03-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('THF', 'Tropical Houseplant Food'), ('BHF', 'Blooming Houseplant Food'), ('IHF', 'Indoor Houseplant Food'), ('NF', 'New Fertilizer'), ('LS', 'Leaf Shine')], default='THF', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='leaf_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light_need',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_type',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_need',
            field=models.TextField(max_length=500),
        ),
    ]
