# Generated by Django 4.2.11 on 2024-03-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_feeding_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='leaf_description',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='toxic',
        ),
    ]
