# Generated by Django 4.2.11 on 2024-03-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_plant_leaf_description_remove_plant_toxic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(default='description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='holders',
            field=models.ManyToManyField(to='main_app.holder'),
        ),
    ]
