# Generated by Django 4.2.11 on 2024-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_holder_plant_description_plant_holders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('THF', 'Tropical Houseplant Food'), ('BHF', 'Blooming Houseplant Food'), ('IHF', 'Indoor Houseplant Food'), ('NF', 'New Fertilizer'), ('LS', 'Leaf Shine'), ('ATT', 'Attention')], default='THF', max_length=5),
        ),
    ]
