# Generated by Django 4.2.11 on 2024-03-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_feeding_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='common_names',
            new_name='common_name',
        ),
    ]
